### ISSUE TITLE
Record support

### ISSUE THREAD

**Issue by Glusha1** [Liversage/Primitives#11]
Dear Martin
Could you please add record support in addition to the struct? Primitives may not have a default value, but with struct there should always be one.

**Comment by Liversage** [comment]
@Glusha1 Can you provide an example of what you mean by "record support"?

You are right that the default value of a struct might break the invariant of the struct but I'm not sure how records fixes that. Records are just classes with some nice properties (and record structs are structs of course).

This library very deliberately uses structs to wrap primitive types like strings and numbers to ensure that the new type you create behave and perform like the underlying primitive type (for the most part).

Do you want a record/class with a single value property that has implicit and/or explicit casts to the type of the value property? That's outside the scope of this library that is focused on generating structs.
